apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: social-media
spec:
  type: NodePort
  selector:
    app: social-media-client
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002