# k8s/server-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: social-media
spec:
  replicas: 2
  selector:
    matchLabels:
      app: social-media-server
  template:
    metadata:
      labels:
        app: social-media-server
    spec:
      containers:
      - name: server
        # This will be replaced by your Docker Hub username
        image: rafaymalik7/social-media-server:latest
        imagePullPolicy: Always  # Always pull the latest image
        ports:
        - containerPort: 4000
        envFrom:
        - configMapRef:
            name: social-media-config
        env:
        - name: MONGO_DB
          valueFrom:
            secretKeyRef:
              name: social-media-secrets
              key: mongo-db
        - name: JWT_KEY
          valueFrom:
            secretKeyRef:
              name: social-media-secrets
              key: jwt-key