apiVersion: v1
kind: Service
metadata:
  name: server  # This matches the docker-compose service name
  namespace: social-media
spec:
  type: ClusterIP
  selector:
    app: social-media-server
  ports:
  - port: 4000
    targetPort: 4000