apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: social-media
spec:
  type: NodePort
  selector:
    app: social-media-server
  ports:
  - port: 4000
    targetPort: 4000
    nodePort: 30001